# THIS CODE IS FOR EDUCATIONAL PURPOSES ONLY #
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install --production
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
      - aws cloudformation deploy --stack-name YOUR_STACK_NAME --template-file outputtemplate.yaml --capabilities CAPABILITY_NAMED_IAM
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml